apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uqcd67urn-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f96aebff43.ka8f.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:acb90aca38e20d33742d65a84e20d3a276f9cf9e@sha256:174474812c3705246bf73f7d3a42ff937f93a784735f16028484bbd3e2130212
          name: container-image
